name: TurfWars
api: 3.9.3​
version: InDEV
main: tufwars\Main
load: POSTWORLD
author: EmreTr1
website: not found


commands:
 turfwars:
  permission: tufwars.command.tw
  description: TurfWars Main Command
  usage: /tw <join|remove|create|leave|help>
